export enum ErrorNames {
  DB_UNKNOWN_ERR = 1,
  DB_REC_NOTFOUND,
  DB_DUP_KEY,
  JWT_FAILED_TO_SIGN,
  JWT_FAILED_TO_DECODE,
  JWT_INVALID,
  JWT_EXPIRED,
  WS_UUID_DUP,
  WS_UUID_NOTFOUND,
  WS_GAMEID_NOTFOUND,
  WS_INVALID_CONN,
  WS_UNKNOWN_ERR,
  WS_COMMAND_NOTFOUND,
  RD_CONN_CLOSED,
  RD_KEY_NOT_FOUND,
  RD_TX_FAILED,
  RD_UNKNOWN,
  BET_NOT_ACTIVE,
  BET_OPTION_NOT_FOUND,
  BET_INSUFFICIENT_BALANCE,
  JSON_UNMARSHAL_ERROR,
  JSON_MARSHAL_ERROR,
  WEBHOOK_ERROR,
}

export function GetErrorName(err: ErrorNames): string {
  return ErrorNames[err];
}
